name: Auto Merge Release PRs

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.user.login == 'github-actions[bot]'
    steps:
      - name: Enable auto-merge for release PRs
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # PR_LABELS: 'autorelease: pending'
          PR_MERGE_METHOD: 'squash'
