name: Deploy Blog

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main 
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      tfpath:
        description: 'TF File Path'     
        required: false
        default: 'ops/terraform'
      hugo_path:
        description: 'Hufo File Path'     
        required: false
        default: 'src'

env:
  AWS_REGION : "us-east-1"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT through OIDC
      contents: read    # This is required for actions/checkout
      
jobs:
  hugo-build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.hugo_path }} 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

  terraform-plan:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    if:  ${{ inputs.tfpath }} 
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_GH_OIDC_ROLE }}
          role-session-name: ${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.job }} 
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform init, plan and apply
        run: |
          echo `pwd`
          echo "tfpath ${{ github.workspace }}/${{ github.event.inputs.tfpath }}"
          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Validate**"
          terraform validate
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.tfpath }}
          
      - name: Terraform Plan
        id: plan
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          terraform plan -no-color >> $GITHUB_STEP_SUMMARY

    # - name: Deploy to S3
    #   run: aws s3 sync public/ s3://${{ steps.terraform.outputs.s3_bucket_name }} --delete
