name: Google - release-please
# https://github.com/google-github-actions/release-please-action
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # release-type: simple
          # monorepo-tags: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          changelog-notes-type: github
